import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { useProtectedPage } from '@/components/AuthProvider';
import CrudActionIcon from '../components/CrudActionIcon';
import PasswordInput from '../components/PasswordInput';
import SettingsLayout from '../components/SettingsLayout';
import { settingsNavItems } from '../components/settingsNav';
import { notifyError, notifySuccess } from '@/utils/notify';
import { getApiBaseUrl } from '@/utils/network';
interface SessionUser {
    id?: number;
    role?: string;
    first_name?: string;
    last_name?: string;
    full_name?: string;
    email?: string;
    username?: string;
    [key: string]: unknown;
}

export default function Settings() {
    const router = useRouter();
    const { user, loading, logout, setSessionUser } = useProtectedPage({
        allowedRoles: ['admin'],
        unauthorizedRedirect: '/dashboard',
    });

    useEffect(() => {
        const section = typeof router.query.section === 'string' ? router.query.section : '';
        if (!section) return;
        const match = settingsNavItems.find((item) => item.id === section);
        if (match && match.id !== 'profile') {
            router.replace(match.path);
        }
    }, [router, router.query.section]);

    if (loading) {
        return (
            <SettingsLayout activeSection="profile" user={user} onLogout={logout}>
                <div style={{ padding: 20 }}>Loading...</div>
            </SettingsLayout>
        );
    }

    return (
        <SettingsLayout activeSection="profile" user={user} onLogout={logout}>
            <AdminProfileSettings
                user={user}
                onUserUpdated={(nextUser) => {
                    setSessionUser((prev) => ({ ...(prev || {}), ...nextUser }));
                }}
            />
        </SettingsLayout>
    );
}

function AdminProfileSettings({
    user,
    onUserUpdated,
}: {
    user: SessionUser | null,
    onUserUpdated: (u: SessionUser) => void,
}) {
    const API_BASE_URL = getApiBaseUrl();
    const isValidGmailComEmail = (value: string) => /^[^\s@]+@(gmail\.com|phinmaed\.com)$/i.test(value.trim());

    const [form, setForm] = useState({
        first_name: user?.first_name || '',
        last_name: user?.last_name || '',
        email: user?.email || '',
        username: user?.username || '',
    });

    const [saving, setSaving] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState<string | null>(null);

    // TOTP state
    const [totpEnabled, setTotpEnabled] = useState<boolean>(false);
    const [totpHasSecret, setTotpHasSecret] = useState<boolean>(false);
    const [totpLoading, setTotpLoading] = useState(false);
    const [showSetup, setShowSetup] = useState(false);
    const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null);
    const [totpSecret, setTotpSecret] = useState<string | null>(null);
    const [pairUrl, setPairUrl] = useState<string | null>(null);

    const [pin, setPin] = useState('');
    const [newPassword, setNewPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [pwLoading, setPwLoading] = useState(false);
    const [pwMsg, setPwMsg] = useState<string | null>(null);
    const [pwErr, setPwErr] = useState<string | null>(null);
    const [totpVerifiedForPwChange, setTotpVerifiedForPwChange] = useState(false);

    useEffect(() => {
        setForm({
            first_name: user?.first_name || '',
            last_name: user?.last_name || '',
            email: user?.email || '',
            username: user?.username || '',
        });
    }, [user?.first_name, user?.last_name, user?.email, user?.username]);

    useEffect(() => {
        if (!error) return;
        void notifyError(error);
        setError(null);
    }, [error]);

    useEffect(() => {
        if (!success) return;
        void notifySuccess(success);
        setSuccess(null);
    }, [success]);

    useEffect(() => {
        if (!pwErr) return;
        void notifyError(pwErr);
        setPwErr(null);
    }, [pwErr]);

    useEffect(() => {
        if (!pwMsg) return;
        void notifySuccess(pwMsg);
        setPwMsg(null);
    }, [pwMsg]);

    // Auto-load TOTP status on mount (secret auto-generated by backend)
    useEffect(() => {
        (async () => {
            try {
                const res = await fetch(`${API_BASE_URL}/auth.php?action=totp_status`, { credentials: 'include' });
                const data = await res.json();
                if (data.success) {
                    setTotpEnabled(!!data.data?.enabled);
                    setTotpHasSecret(!!data.data?.hasSecret);
                    if (data.data?.qrCodeUrl) setQrCodeUrl(data.data.qrCodeUrl);
                    if (data.data?.secret) setTotpSecret(data.data.secret);
                }
            } catch { }
        })();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const saveProfile = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);
        setSuccess(null);

        const payload = {
            first_name: form.first_name.trim(),
            last_name: form.last_name.trim(),
            email: form.email.trim().toLowerCase(),
            username: form.username.trim(),
        };

        if (!payload.username) {
            setError('Username is required.');
            return;
        }
        if (!isValidGmailComEmail(payload.email)) {
            setError('Email must be a valid @gmail.com or @phinmaed.com address.');
            return;
        }

        setSaving(true);
        try {
            const res = await fetch(`${API_BASE_URL}/auth.php?action=admin_update_profile`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                credentials: 'include',
                body: JSON.stringify(payload),
            });
            const data = await res.json();
            if (data.success) {
                setSuccess(data.message || 'Profile updated.');
                onUserUpdated({ ...user, ...data.data });
            } else {
                setError(data.message || 'Failed to update profile.');
            }
        } catch (err) {
            console.error(err);
            setError('Network error.');
        } finally {
            setSaving(false);
        }
    };

    // Step 1: Generate pairing (QR code + secret)
    const startSetup = async (regenerate = false) => {
        setPwErr(null);
        setPwMsg(null);
        setTotpLoading(true);
        try {
            const res = await fetch(`${API_BASE_URL}/auth.php?action=totp_pair`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                credentials: 'include',
                body: JSON.stringify({ regenerate }),
            });
            const data = await res.json();
            if (data.success) {
                setQrCodeUrl(data.data?.qrCodeUrl || null);
                setTotpSecret(data.data?.secret || null);
                setPairUrl(data.data?.pairUrl || null);
                setTotpEnabled(!!data.data?.enabled);
                setTotpHasSecret(true);
                setShowSetup(true);
            } else {
                setPwErr(data.message || 'Failed to generate pairing.');
            }
        } catch (err) {
            console.error(err);
            setPwErr('Network error.');
        } finally {
            setTotpLoading(false);
        }
    };

    // Step 2: Verify PIN to enable TOTP
    const verifyPin = async () => {
        setPwErr(null);
        setPwMsg(null);

        const trimmedPin = pin.trim().replace(/\D/g, '');
        if (trimmedPin.length !== 6) {
            setPwErr('Enter a valid 6-digit code from your authenticator app.');
            return;
        }

        setPwLoading(true);
        try {
            const res = await fetch(`${API_BASE_URL}/auth.php?action=totp_validate`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                credentials: 'include',
                body: JSON.stringify({ pin: trimmedPin }),
            });
            const data = await res.json();
            if (data.success) {
                setTotpEnabled(true);
                setPwMsg('✅ Google Authenticator enabled! You can now use it to reset your password.');
                setPin('');
                setShowSetup(false);
            } else {
                setPwErr(data.message || 'Invalid code. Make sure your authenticator app has the correct time.');
            }
        } catch (err) {
            console.error(err);
            setPwErr('Network error.');
        } finally {
            setPwLoading(false);
        }
    };

    // Change password using TOTP
    const changePasswordWithTOTP = async (e: React.FormEvent) => {
        e.preventDefault();
        setPwErr(null);
        setPwMsg(null);

        const trimmedPin = pin.trim().replace(/\D/g, '');
        if (trimmedPin.length !== 6) {
            setPwErr('Enter a valid 6-digit authenticator code.');
            return;
        }
        if (!newPassword || newPassword.length < 8) {
            setPwErr('New password must be at least 8 characters.');
            return;
        }
        if (newPassword !== confirmPassword) {
            setPwErr('Passwords do not match.');
            return;
        }

        setPwLoading(true);
        try {
            const res = await fetch(`${API_BASE_URL}/auth.php?action=change_password_with_totp`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                credentials: 'include',
                body: JSON.stringify({ pin: trimmedPin, newPassword }),
            });
            const data = await res.json();
            if (data.success) {
                setPwMsg(data.message || 'Password changed successfully.');
                setPin('');
                setNewPassword('');
                setConfirmPassword('');
            } else {
                setPwErr(data.message || 'Failed to change password.');
            }
        } catch (err) {
            console.error(err);
            setPwErr('Network error.');
        } finally {
            setPwLoading(false);
        }
    };

    return (
        <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
            gap: 14,
            alignItems: 'start',
            width: '100%',
            minWidth: 0,
        }}>
            <div style={{ display: 'grid', gap: 14, alignContent: 'start' }}>
                {/* ---- Profile ---- */}
                <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 12, padding: 14, minWidth: 0 }}>
                    <h2 style={{ margin: 0, marginBottom: 10, fontSize: 14, fontWeight: 700, color: '#111827' }}>Profile</h2>

                    <form onSubmit={saveProfile} style={{ display: 'grid', gap: 10 }}>
                        <div style={{ display: 'grid', gap: 6 }}>
                            <label style={{ fontSize: 13, color: '#374151' }}>Username</label>
                            <input
                                value={form.username}
                                onChange={(e) => setForm((p) => ({ ...p, username: e.target.value }))}
                                style={{ padding: '9px 11px', borderRadius: 10, border: '1px solid #d1d5db' }}
                                disabled={saving}
                            />
                        </div>

                        <div style={{ display: 'grid', gap: 6 }}>
                            <label style={{ fontSize: 13, color: '#374151' }}>Email</label>
                            <input
                                type="email"
                                value={form.email}
                                onChange={(e) => setForm((p) => ({ ...p, email: e.target.value }))}
                                pattern="^[^\s@]+@(gmail\.com|phinmaed\.com)$"
                                title="Use a valid @gmail.com or @phinmaed.com email address."
                                placeholder="example@phinmaed.com"
                                style={{ padding: '9px 11px', borderRadius: 10, border: '1px solid #d1d5db' }}
                                disabled={saving}
                            />
                        </div>

                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 10 }}>
                            <div style={{ display: 'grid', gap: 6 }}>
                                <label style={{ fontSize: 13, color: '#374151' }}>First name</label>
                                <input
                                    value={form.first_name}
                                    onChange={(e) => setForm((p) => ({ ...p, first_name: e.target.value }))}
                                    style={{ padding: '9px 11px', borderRadius: 10, border: '1px solid #d1d5db' }}
                                    disabled={saving}
                                />
                            </div>
                            <div style={{ display: 'grid', gap: 6 }}>
                                <label style={{ fontSize: 13, color: '#374151' }}>Last name</label>
                                <input
                                    value={form.last_name}
                                    onChange={(e) => setForm((p) => ({ ...p, last_name: e.target.value }))}
                                    style={{ padding: '9px 11px', borderRadius: 10, border: '1px solid #d1d5db' }}
                                    disabled={saving}
                                />
                            </div>
                        </div>

                        <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                            <button
                                type="submit"
                                disabled={saving}
                                title="Save changes"
                                aria-label="Save changes"
                                style={{
                                    background: '#1e3a8a',
                                    color: '#fff',
                                    border: 'none',
                                    padding: '9px 12px',
                                    borderRadius: 10,
                                    cursor: 'pointer',
                                    opacity: saving ? 0.7 : 1,
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                }}
                            >
                                {saving ? 'Saving...' : 'Submit'}
                            </button>
                        </div>
                    </form>
                </div>

            </div>

            {/* ---- Two-Factor Authentication (Google Authenticator) ---- */}
            <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 12, padding: 12, minWidth: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6, flexWrap: 'wrap' }}>
                    <h2 style={{ margin: 0, fontSize: 14, fontWeight: 700, color: '#111827' }}>
                        Two-Factor Authentication
                    </h2>
                    <span style={{
                        display: 'inline-block',
                        padding: '2px 8px',
                        borderRadius: 999,
                        fontSize: 10,
                        fontWeight: 600,
                        background: '#dcfce7',
                        color: '#166534',
                        border: '1px solid #86efac',
                    }}>
                        ✓ Active
                    </span>
                </div>

                <p style={{ marginTop: 0, marginBottom: 10, fontSize: 12, lineHeight: 1.5, color: '#6b7280' }}>
                    Google Authenticator is active. Scan the code below, then verify with a 6-digit code before changing your password.
                </p>

                {/* QR Code - always visible */}
                <div style={{
                    background: '#f9fafb',
                    border: '1px solid #e5e7eb',
                    borderRadius: 10,
                    padding: 10,
                    marginBottom: 10,
                }}>
                    <h3 style={{ margin: '0 0 8px 0', fontSize: 12, fontWeight: 700, color: '#111827' }}>
                        Scan with Google Authenticator
                    </h3>

                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, alignItems: 'flex-start' }}>
                        {/* QR Code */}
                        {qrCodeUrl && (
                            <div style={{
                                background: '#fff',
                                border: '1px solid #d1d5db',
                                borderRadius: 8,
                                padding: 5,
                                display: 'inline-flex',
                                width: 136,
                                flex: '0 0 136px',
                            }}>
                                {/* eslint-disable-next-line @next/next/no-img-element */}
                                <img
                                    src={qrCodeUrl}
                                    alt="Scan this QR code with Google Authenticator"
                                    width={126}
                                    height={126}
                                    style={{ display: 'block', width: '100%', height: 'auto' }}
                                />
                            </div>
                        )}

                        <div style={{ minWidth: 0, flex: '1 1 220px' }}>
                            <p style={{ margin: '0 0 4px 0', fontSize: 11.5, color: '#374151' }}>
                                1. Open <strong>Google Authenticator</strong> on your phone
                            </p>
                            <p style={{ margin: '0 0 4px 0', fontSize: 11.5, color: '#374151' }}>
                                2. Tap <strong>+</strong>, then <strong>Scan QR code</strong>
                            </p>
                            <p style={{ margin: '0 0 8px 0', fontSize: 11.5, color: '#374151' }}>
                                3. Scan the QR code shown here
                            </p>

                            {totpSecret && (
                                <div style={{ marginBottom: 10 }}>
                                    <div style={{ fontSize: 11, color: '#6b7280', marginBottom: 4 }}>
                                        Manual setup key
                                    </div>
                                    <code style={{
                                        display: 'inline-block',
                                        background: '#fff',
                                        border: '1px solid #d1d5db',
                                        borderRadius: 6,
                                        padding: '5px 8px',
                                        fontSize: 11,
                                        letterSpacing: 1.2,
                                        fontFamily: 'monospace',
                                        color: '#111827',
                                        wordBreak: 'break-all',
                                        userSelect: 'all',
                                        maxWidth: '100%',
                                    }}>
                                        {totpSecret}
                                    </code>
                                </div>
                            )}

                            {/* Re-pair button */}
                            <button
                                type="button"
                                onClick={() => startSetup(true)}
                                disabled={totpLoading}
                                style={{
                                    background: 'transparent',
                                    border: '1px solid #d1d5db',
                                    padding: '5px 9px',
                                    borderRadius: 8,
                                    cursor: 'pointer',
                                    fontSize: 11.5,
                                    color: '#374151',
                                    opacity: totpLoading ? 0.5 : 1,
                                }}
                            >
                                {totpLoading ? 'Regenerating...' : 'Regenerate QR'}
                            </button>
                        </div>
                    </div>
                </div>

                {/* Change password section - always visible */}
                <div style={{
                    background: '#f9fafb',
                    border: '1px solid #e5e7eb',
                    borderRadius: 10,
                    padding: 10,
                }}>
                    <h3 style={{ margin: '0 0 8px 0', fontSize: 12, fontWeight: 700, color: '#111827' }}>
                        Change password with authenticator
                    </h3>

                    {/* Step 1: Verify authenticator code first */}
                    {!totpVerifiedForPwChange && (
                        <div style={{ display: 'grid', gap: 8 }}>
                            <p style={{ margin: 0, fontSize: 12, lineHeight: 1.5, color: '#6b7280' }}>
                                Verify your identity with a 6-digit code before changing your password.
                            </p>
                            <div style={{ display: 'flex', gap: 8, alignItems: 'end', flexWrap: 'wrap' }}>
                                <div style={{ display: 'grid', gap: 6, flex: '1 1 170px', minWidth: 0 }}>
                                    <label style={{ fontSize: 12, color: '#374151' }}>Authenticator code</label>
                                    <input
                                        value={pin}
                                        onChange={(e) => setPin(e.target.value.replace(/\D/g, '').slice(0, 6))}
                                        inputMode="numeric"
                                        maxLength={6}
                                        style={{
                                            padding: '8px 10px',
                                            borderRadius: 10,
                                            border: '1px solid #d1d5db',
                                            fontFamily: 'monospace',
                                            letterSpacing: 3,
                                            textAlign: 'center',
                                            fontSize: 13,
                                            width: '100%',
                                            maxWidth: 160,
                                        }}
                                        placeholder="000000"
                                        disabled={pwLoading}
                                        autoFocus
                                    />
                                </div>
                                <button
                                    type="button"
                                    disabled={pwLoading || pin.length !== 6}
                                    onClick={async () => {
                                        setPwErr(null);
                                        setPwMsg(null);
                                        const trimmedPin = pin.trim().replace(/\D/g, '');
                                        if (trimmedPin.length !== 6) {
                                            setPwErr('Enter a valid 6-digit code from your authenticator app.');
                                            return;
                                        }
                                        setPwLoading(true);
                                        try {
                                            const res = await fetch(`${API_BASE_URL}/auth.php?action=totp_validate`, {
                                                method: 'POST',
                                                headers: { 'Content-Type': 'application/json' },
                                                credentials: 'include',
                                                body: JSON.stringify({ pin: trimmedPin }),
                                            });
                                            const data = await res.json();
                                            if (data.success) {
                                                setTotpVerifiedForPwChange(true);
                                                setPwMsg('✅ Identity verified! You can now set your new password.');
                                                setPin('');
                                            } else {
                                                setPwErr(data.message || 'Invalid code. Please try again.');
                                            }
                                        } catch (err) {
                                            console.error(err);
                                            setPwErr('Network error.');
                                        } finally {
                                            setPwLoading(false);
                                        }
                                    }}
                                    style={{
                                        background: '#1e3a8a',
                                        color: '#fff',
                                        border: 'none',
                                        padding: '8px 12px',
                                        borderRadius: 10,
                                        cursor: 'pointer',
                                        fontSize: 12,
                                        fontWeight: 600,
                                        opacity: (pwLoading || pin.length !== 6) ? 0.5 : 1,
                                    }}
                                >
                                    {pwLoading ? 'Verifying...' : 'Verify code'}
                                </button>
                            </div>
                        </div>
                    )}

                    {/* Step 2: Password fields (shown after code is verified) */}
                    {totpVerifiedForPwChange && (
                        <div>
                            <div style={{
                                display: 'flex', alignItems: 'center', gap: 8,
                                marginBottom: 10, padding: '6px 9px',
                                background: '#dcfce7', border: '1px solid #86efac', borderRadius: 8,
                            }}>
                                <span style={{ fontSize: 12, color: '#166534', fontWeight: 600 }}>Identity verified</span>
                                <button
                                    type="button"
                                    onClick={() => { setTotpVerifiedForPwChange(false); setPin(''); setNewPassword(''); setConfirmPassword(''); setPwErr(null); setPwMsg(null); }}
                                    style={{ marginLeft: 'auto', fontSize: 12, color: '#6b7280', background: 'transparent', border: 'none', cursor: 'pointer', textDecoration: 'underline' }}
                                >
                                    Back
                                </button>
                            </div>

                            <form onSubmit={changePasswordWithTOTP} style={{ display: 'grid', gap: 10 }}>
                                <div style={{ display: 'grid', gap: 6 }}>
                                    <label style={{ fontSize: 12, color: '#374151' }}>Authenticator code</label>
                                    <input
                                        value={pin}
                                        onChange={(e) => setPin(e.target.value.replace(/\D/g, '').slice(0, 6))}
                                        inputMode="numeric"
                                        maxLength={6}
                                        style={{ padding: '8px 10px', borderRadius: 10, border: '1px solid #d1d5db', fontFamily: 'monospace', letterSpacing: 2 }}
                                        placeholder="6-digit code"
                                        disabled={pwLoading}
                                    />
                                </div>

                                <div style={{ display: 'grid', gap: 6 }}>
                                    <label style={{ fontSize: 12, color: '#374151' }}>New password</label>
                                    <PasswordInput
                                        value={newPassword}
                                        onChange={(e) => setNewPassword(e.target.value)}
                                        style={{ padding: '8px 10px', borderRadius: 10, border: '1px solid #d1d5db' }}
                                        disabled={pwLoading}
                                    />
                                </div>

                                <div style={{ display: 'grid', gap: 6 }}>
                                    <label style={{ fontSize: 12, color: '#374151' }}>Confirm password</label>
                                    <PasswordInput
                                        value={confirmPassword}
                                        onChange={(e) => setConfirmPassword(e.target.value)}
                                        style={{ padding: '8px 10px', borderRadius: 10, border: '1px solid #d1d5db' }}
                                        disabled={pwLoading}
                                    />
                                </div>

                                <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                                    <button
                                        type="submit"
                                        disabled={pwLoading}
                                        title="Update password"
                                        aria-label="Update password"
                                        style={{
                                            background: '#111827',
                                            color: '#fff',
                                            border: 'none',
                                            padding: '8px 11px',
                                            borderRadius: 10,
                                            cursor: 'pointer',
                                            opacity: pwLoading ? 0.7 : 1,
                                            display: 'inline-flex',
                                            alignItems: 'center',
                                            justifyContent: 'center',
                                        }}
                                    >
                                        {pwLoading ? 'Updating...' : 'Submit'}
                                    </button>
                                </div>
                            </form>
                        </div>
                    )}
                </div>

            </div>
        </div>
    );
}
